openapi: 3.0.0
info:
  x-skaffolder-id-project: 5ed8f81d1b44472d126f1cc8
  title: GIARDINO
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  /foto_fiore:
    post:
      x-skaffolder-id: 5ed8fd161b44472d126f1d82
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5ed8fa4d1b44472d126f1d79
      x-skaffolder-resource: foto_fiore
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - foto_fiore
      parameters:
        - name: obj
          x-skaffolder-type: foto_fiore
          in: path
          description: Object to insert
          required: true
          schema:
            type: foto_fiore
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/foto_fiore"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                altezza:
                  type: number
                colore:
                  type: string
                nome:
                  type: string
                periodo_fioritura:
                  type: string
    get:
      x-skaffolder-id: 5ed8fd241b44472d126f1d86
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5ed8fa4d1b44472d126f1d79
      x-skaffolder-resource: foto_fiore
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: ARRAY OF foto_fiore
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - foto_fiore
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/foto_fiore"
  "/foto_fiore/{id}":
    delete:
      x-skaffolder-id: 5ed8fd1f1b44472d126f1d84
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5ed8fa4d1b44472d126f1d79
      x-skaffolder-resource: foto_fiore
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - foto_fiore
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id foto_fiore
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5ed8fd281b44472d126f1d87
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5ed8fa4d1b44472d126f1d79
      x-skaffolder-resource: foto_fiore
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: foto_fiore
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - foto_fiore
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id foto_fiore
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/foto_fiore"
    post:
      x-skaffolder-id: 5ed8fd421b44472d126f1d89
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5ed8fa4d1b44472d126f1d79
      x-skaffolder-resource: foto_fiore
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: foto_fiore
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - foto_fiore
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id foto_fiore
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/foto_fiore"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/foto_fiore"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    foto_fiore:
      x-skaffolder-id: 5ed8fa4d1b44472d126f1d79
      x-skaffolder-id-db: 5ed8f81d1b44472d126f1cc9
      x-skaffolder-id-entity: 5ed8fa4d1b44472d126f1d74
      x-skaffolder-url: /foto_fiore
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        altezza:
          type: number
          x-skaffolder-id-attr: 5ed8fa4d1b44472d126f1d75
          x-skaffolder-type: Number
        colore:
          type: string
          x-skaffolder-id-attr: 5ed8fa4d1b44472d126f1d76
          x-skaffolder-type: String
        nome:
          type: string
          x-skaffolder-id-attr: 5ed8fa4d1b44472d126f1d78
          x-skaffolder-type: String
        periodo_fioritura:
          type: string
          x-skaffolder-id-attr: 5ed8fa4d1b44472d126f1d77
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
  x-skaffolder-db:
    - x-skaffolder-id: 5ed8f81d1b44472d126f1cc9
      x-skaffolder-name: GIARDINO_db
  x-skaffolder-page:
    - x-skaffolder-id: 5ed8fae41b44472d126f1d7e
      x-skaffolder-name: FotoFiore
      x-skaffolder-url: /fotoFiore
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5ed8fbb71b44472d126f1d81
      x-skaffolder-roles: []
    - x-skaffolder-id: 5ed8fbb71b44472d126f1d81
      x-skaffolder-name: FotoFioreEdit
      x-skaffolder-url: /fotoFioreEdit
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 5ed8f81d1b44472d126f1cd1
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5ed8fae41b44472d126f1d7e
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 5ed8f81e1b44472d126f1cd4
      x-skaffolder-name: ADMIN
